apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
  namespace: web
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
  selector:
    run: tripviewer
  type: NodePort