apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: insurance-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: insurance
          servicePort: 80
        path: /