apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  namespace: api
spec:
  selector:
    matchLabels:
      run: user-java
  replicas: 1
  template:
    metadata:
      labels:
        run: user-java
    spec:
      containers:
      - name: user-java
        image: registryrdz2161.azurecr.io/user-java:1.0
        ports:
        - containerPort: 80
        env:
        - name: SQL_SERVER
          value: sqlserverrdz2161.database.windows.net
        - name: SQL_DBNAME
          value: mydrivingDB
        # - name: PORT
        #   value: 80
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "sql-creds"
            nodePublishSecretRef:                       # Only required when using service principal mode
              name: secrets-store-creds                 # Only required when using service principal mode
