apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    run: poi
  type: ClusterIP